/*BEGIN_LEGAL 
Copyright 2002-2020 Intel Corporation.

This software and the related documents are Intel copyrighted materials, and your
use of them is governed by the express license under which they were provided to
you ("License"). Unless the License provides otherwise, you may not use, modify,
copy, publish, distribute, disclose or transmit this software or the related
documents without Intel's prior written permission.

This software and the related documents are provided as is, with no express or
implied warranties, other than those that are expressly stated in the License.
END_LEGAL */
/// @file xed-init-pointer-names.h

// This file was automatically generated.
// Do not edit this file.

#if !defined(XED_INIT_POINTER_NAMES_H)
# define XED_INIT_POINTER_NAMES_H
#include "xed-internal-header.h"
#define XED_MAX_POINTER_NAMES 65
#endif
