/*BEGIN_LEGAL 
Copyright 2002-2020 Intel Corporation.

This software and the related documents are Intel copyrighted materials, and your
use of them is governed by the express license under which they were provided to
you ("License"). Unless the License provides otherwise, you may not use, modify,
copy, publish, distribute, disclose or transmit this software or the related
documents without Intel's prior written permission.

This software and the related documents are provided as is, with no express or
implied warranties, other than those that are expressly stated in the License.
END_LEGAL */
/// @file xed-operand-type-enum.h

// This file was automatically generated.
// Do not edit this file.

#if !defined(XED_OPERAND_TYPE_ENUM_H)
# define XED_OPERAND_TYPE_ENUM_H
#include "xed-common-hdrs.h"
#define XED_OPERAND_TYPE_INVALID_DEFINED 1
#define XED_OPERAND_TYPE_ERROR_DEFINED 1
#define XED_OPERAND_TYPE_IMM_DEFINED 1
#define XED_OPERAND_TYPE_IMM_CONST_DEFINED 1
#define XED_OPERAND_TYPE_NT_LOOKUP_FN_DEFINED 1
#define XED_OPERAND_TYPE_NT_LOOKUP_FN2_DEFINED 1
#define XED_OPERAND_TYPE_NT_LOOKUP_FN4_DEFINED 1
#define XED_OPERAND_TYPE_REG_DEFINED 1
#define XED_OPERAND_TYPE_LAST_DEFINED 1
typedef enum {
  XED_OPERAND_TYPE_INVALID,
  XED_OPERAND_TYPE_ERROR,
  XED_OPERAND_TYPE_IMM,
  XED_OPERAND_TYPE_IMM_CONST,
  XED_OPERAND_TYPE_NT_LOOKUP_FN,
  XED_OPERAND_TYPE_NT_LOOKUP_FN2,
  XED_OPERAND_TYPE_NT_LOOKUP_FN4,
  XED_OPERAND_TYPE_REG,
  XED_OPERAND_TYPE_LAST
} xed_operand_type_enum_t;

/// This converts strings to #xed_operand_type_enum_t types.
/// @param s A C-string.
/// @return #xed_operand_type_enum_t
/// @ingroup ENUM
XED_DLL_EXPORT xed_operand_type_enum_t str2xed_operand_type_enum_t(const char* s);
/// This converts strings to #xed_operand_type_enum_t types.
/// @param p An enumeration element of type xed_operand_type_enum_t.
/// @return string
/// @ingroup ENUM
XED_DLL_EXPORT const char* xed_operand_type_enum_t2str(const xed_operand_type_enum_t p);

/// Returns the last element of the enumeration
/// @return xed_operand_type_enum_t The last element of the enumeration.
/// @ingroup ENUM
XED_DLL_EXPORT xed_operand_type_enum_t xed_operand_type_enum_t_last(void);
#endif
