/*BEGIN_LEGAL 
Copyright 2002-2020 Intel Corporation.

This software and the related documents are Intel copyrighted materials, and your
use of them is governed by the express license under which they were provided to
you ("License"). Unless the License provides otherwise, you may not use, modify,
copy, publish, distribute, disclose or transmit this software or the related
documents without Intel's prior written permission.

This software and the related documents are provided as is, with no express or
implied warranties, other than those that are expressly stated in the License.
END_LEGAL */
/// @file xed-encoder-gen-defs.h

// This file was automatically generated.
// Do not edit this file.

#if !defined(XED_ENCODER_GEN_DEFS_H)
# define XED_ENCODER_GEN_DEFS_H
#define XED_ENCODE_ORDER_MAX_ENTRIES  32
#define XED_ENCODE_ORDER_MAX_OPERANDS 5
#define XED_ENCODE_MAX_FB_PATTERNS 120
#define XED_ENCODE_MAX_EMIT_PATTERNS 185
#define XED_ENCODE_FB_VALUES_TABLE_SIZE 3268
#define XED_ENCODE_MAX_IFORMS 7043
#define XED_ENC_GROUPS 505
#endif
