/*BEGIN_LEGAL 
Copyright 2002-2020 Intel Corporation.

This software and the related documents are Intel copyrighted materials, and your
use of them is governed by the express license under which they were provided to
you ("License"). Unless the License provides otherwise, you may not use, modify,
copy, publish, distribute, disclose or transmit this software or the related
documents without Intel's prior written permission.

This software and the related documents are provided as is, with no express or
implied warranties, other than those that are expressly stated in the License.
END_LEGAL */
/// @file xed-gen-table-defs.h

// This file was automatically generated.
// Do not edit this file.

#if !defined(XED_GEN_TABLE_DEFS_H)
# define XED_GEN_TABLE_DEFS_H
#define XED_ICLASS_NAME_STR_MAX 142
#define XED_MAX_ATTRIBUTE_COUNT 89
#define XED_MAX_INST_TABLE_NODES 7018
#define XED_MAX_OPERAND_TABLE_NODES 1444
#define XED_MAX_OPERAND_SEQUENCES 8238
#define XED_MAX_REQUIRED_SIMPLE_FLAGS_ENTRIES 96
#define XED_MAX_REQUIRED_COMPLEX_FLAGS_ENTRIES 37
#define XED_MAX_GLOBAL_FLAG_ACTIONS 460
#define XED_MAX_IFORMS_PER_ICLASS 28
#define XED_MAX_REQUIRED_ATTRIBUTES 191
#define XED_MAX_CONVERT_PATTERNS 5
#define XED_MAX_DECORATIONS_PER_OPERAND 3
#define XED_MAX_MAP_VEX  3
#define XED_MAX_MAP_EVEX 3
#endif
