# Configuration for access information
# Default values: any omiited user id and ssh key will use those values

# pull this repo as:
# git clone git@tscript.github.com:shsym/mind.git

# This is an example configuration that we used for our cluster
default:
  script root: ~/mind_ae_fastswap/ctrl_scripts/
  user: sosp_ae
  key: ~/.ssh/vmhost_acc
  cluster gw: 10.10.10.0
  nic: ens9
  control ip: 172.29.249.30

# id of switch must be -1
switch:
- switch1:
  id: -1
  control ip: 172.29.249.42   # control plane IP
  cluster ip: 10.10.10.1      # data plane IP
  # user: sslee                 # user to login
  # key: ~/.ssh/switch_acc      # ssh key to use for logging in

# list of compute servers
compute servers:
- c_server1:
  id: 1   # server's id
  control ip: 172.28.229.148
  cluster ip: 10.10.10.201
  nic: ens8f0                 # a network interface for copying data
  user: sosp_ae
  key: ~/.ssh/vmhost_acc
  data_onwer: sslee           # owner of the memory traces
  vm list:
    - vm1:
      id: 101
      control ip: 192.168.122.211
      cluster ip: 10.10.10.201
      mac: 04:3f:72:a2:b4:a2
      vm name: fastswap_client_01
      user: root
      key: ~/.ssh/id_rsa_for_vm

# list of memory servers
memory servers:
  - m_server1:
    control ip: 172.29.249.30
    vm list:
      - vm1:
        id: 16
        control ip: 192.168.122.61
        cluster ip: 10.10.10.221
        mac: 04:3f:72:a2:b7:3a
        vm name: fastswap_server_01
        user: root
        nic: ens10

# list of storage servers
storage servers:
- s_server1:
  control ip: 172.29.249.44
  cluster ip: 10.10.10.212
  mac: 04:3f:72:a2:b4:3b
  user: sosp_ae
  key: ~/.ssh/disagg_comp
  trace src:
    tf: /home/yanpeng/2020_11_25_tensorflow/
    gc: /home/yanpeng/2021_03_graphchi/
    ma: /media/data_ssds/memcached_a/
    mc: /media/data_ssds/memcached_c/
  trace dst:
    tf:
      dir_1: /media/data_ssds/tensorflow_logs/
      dir_2: /media/data_raid0/tensorflow_logs/
    gc:
      dir_1: /media/data_ssds/graphchi_logs/
      dir_2: /media/data_raid0/graphchi_logs/
    ma:
      dir_1: /media/data_ssds/memcached_a_logs/
      dir_2: /media/data_raid0/memcached_a_logs/
    mc:
      dir_1: /media/data_ssds/memcached_c_logs/
      dir_2: /media/data_raid0/memcached_c_logs/
